name: Maven Tests

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to execute'
        required: true
        default: '@happypath'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Install dependencies for headless Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable libxss1 libappindicator3-1 libgdk-pixbuf2.0-0 libgbm-dev

      - name: Grant permission to mvnw
        run: chmod +x mvnw

      - name: Run tests with tag
        run: mvn clean test -Dcucumber.options="--tags @${{ github.event.inputs.tag }}"
