name: Run Tests by Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to run (e.g. @unhappypath)'
        required: true
        default: '@happypath'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install dependencies for headless Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable libxss1 libappindicator3-1 libgdk-pixbuf2.0-0 libgbm-dev

      - name: Grant permission to mvnw
        run: chmod +x mvnw

      - name: Run tests with Maven and tag
        run: mvn clean test -Dcucumber.options="--tags @${{ github.event.inputs.tag }}"

      - name: Upload Serenity Reports
        uses: actions/upload-artifact@v3
        with:
          name: serenity-report
          path: target/serenity-reports
